#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'imgui'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'imgui.cpp',
		'imgui_draw.cpp',
		'imgui_tables.cpp',
		'imgui_widgets.cpp',
		'backends/imgui_impl_sdl2.cpp',
		'backends/imgui_impl_opengl3.cpp',
	]

	includes = [
		'.',
		'./backend',
	] + bld.env.INCLUDES_SDL2

	defines = []

	libs = []

	install_path = None if bld.env.BUILD_SDK else bld.env.LIBDIR

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		install_path = install_path,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

